---
title: "R for Everyone Project"
output: html_notebook
---
```{r}
library(tidyverse)
hospitals <- read_csv("data/hospitals.csv")
```

```{r}
ca_hospitals <- hospitals%>%
  filter(Facility.State=="CA")
```

```{r}
ca_hospitals
```
```{r}
ca_church <- ca_hospitals%>%filter(Facility.Type == "Church")
ca_private <- ca_hospitals%>%filter(Facility.Type == "Private")
ca_proprietary <- ca_hospitals%>%filter(Facility.Type == "Proprietary")
ca_government <- ca_hospitals%>%filter(Facility.Type == "Government")
ca_unknown <- ca_hospitals%>%filter(Facility.Type == "Unknown")
```

```{r}
library(RColorBrewer)
myPalette <- brewer.pal(5, "Set1") 
num_facility_type <- c(nrow(ca_church), nrow(ca_private), nrow(ca_proprietary), nrow(ca_government), nrow(ca_unknown))

pie(num_facility_type, labels = c("Church","Private","Proprietary","Government","Unknown"), border="white", col=myPalette)
```

```{r}
facility_type <- c("Church","Private","Proprietary","Government","Unknown")
facility_rating <- c(mean(ca_church$Rating.Overall), 
                     mean(ca_private$Rating.Overall), 
                     mean(ca_proprietary$Rating.Overall), 
                     mean(ca_government$Rating.Overall),
                     mean(ca_unknown$Rating.Overall))
                     
bar_facility <- data.frame(facility_type, facility_rating)
ggplot(bar_facility)+geom_col(mapping=aes(x=facility_type, fill = facility_type, y=facility_rating))+
  scale_x_discrete(guide = guide_axis(angle = 90))+
  ggtitle("Mean Overall Ratings of Medical Facilities in CA by Facility Type")+
  xlab("Facility Type")+
  ylab("Mean Overall Ratings")
```


```{r}
san_francisco_hospitals <- ca_hospitals%>%
  filter(Facility.City=="San Francisco")
```

```{r}
sf_facilities <- san_francisco_hospitals$Facility.Name
sf_hip <- san_francisco_hospitals$`Procedure.Hip Knee.Cost`
bar <- data.frame(sf_facilities, sf_hip)
ggplot(bar)+geom_col(mapping=aes(x=sf_facilities, fill=sf_facilities, y=sf_hip))+
  scale_x_discrete(guide = guide_axis(angle = 90))+
  ggtitle("Cost of Hip-Knee Procedure by Medical Facility in SF")+
  xlab("Name of Medical Facility")+
  ylab("Cost of Procedure")
```

```{r}
sf_rating <- san_francisco_hospitals$Rating.Overall
bar1 <- data.frame(sf_facilities, sf_rating)
ggplot(bar1)+geom_col(mapping=aes(x=sf_facilities, fill = sf_facilities, y=sf_rating))+
  scale_x_discrete(guide = guide_axis(angle = 90))+
  ggtitle("Overall Ratings of Medical Facilities in SF")+
  xlab("Name of Medical Facility")+
  ylab("Overall Ratings")
```

```{r}
AL<- hospitals%>%filter(Facility.State == "AL")
AK<- hospitals%>%filter(Facility.State == "AK")
AZ<- hospitals%>%filter(Facility.State == "AZ")
AR<- hospitals%>%filter(Facility.State == "AR")
CA<- hospitals%>%filter(Facility.State == "CA")
CO<- hospitals%>%filter(Facility.State == "CO")
CT<- hospitals%>%filter(Facility.State == "CT")
DE<- hospitals%>%filter(Facility.State == "DE")
DC<- hospitals%>%filter(Facility.State == "DC")
FL<- hospitals%>%filter(Facility.State == "FL")
GA<- hospitals%>%filter(Facility.State == "GA")
HI<- hospitals%>%filter(Facility.State == "HI")
ID<- hospitals%>%filter(Facility.State == "ID")
IL<- hospitals%>%filter(Facility.State == "IL")
IN<- hospitals%>%filter(Facility.State == "IN")
IA<- hospitals%>%filter(Facility.State == "IA")
KS<- hospitals%>%filter(Facility.State == "KS")
KY<- hospitals%>%filter(Facility.State == "KY")
LA<- hospitals%>%filter(Facility.State == "LA")
ME<- hospitals%>%filter(Facility.State == "ME")
MD<- hospitals%>%filter(Facility.State == "MD")
MA<- hospitals%>%filter(Facility.State == "MA")
MI<- hospitals%>%filter(Facility.State == "MN")
MS<- hospitals%>%filter(Facility.State == "MS")
MO<- hospitals%>%filter(Facility.State == "MO")
MT<- hospitals%>%filter(Facility.State == "MT")
NE<- hospitals%>%filter(Facility.State == "NE")
NV<- hospitals%>%filter(Facility.State == "NV")
NH<- hospitals%>%filter(Facility.State == "NH")
NJ<- hospitals%>%filter(Facility.State == "NJ")
NM<- hospitals%>%filter(Facility.State == "NM")
NY<- hospitals%>%filter(Facility.State == "NY")
NC<- hospitals%>%filter(Facility.State == "NC")
ND<- hospitals%>%filter(Facility.State == "ND")
OH<- hospitals%>%filter(Facility.State == "OH")
OK<- hospitals%>%filter(Facility.State == "OK")
OR<- hospitals%>%filter(Facility.State == "OR")
PA<- hospitals%>%filter(Facility.State == "PA")
PR<- hospitals%>%filter(Facility.State == "PR")
RI<- hospitals%>%filter(Facility.State == "RI")
SC<- hospitals%>%filter(Facility.State == "SC")
SD<- hospitals%>%filter(Facility.State == "SD")
TN<- hospitals%>%filter(Facility.State == "TN")
TX<- hospitals%>%filter(Facility.State == "TX")
UT<- hospitals%>%filter(Facility.State == "UT")
VT<- hospitals%>%filter(Facility.State == "VT")
VI<- hospitals%>%filter(Facility.State == "VI")
VA<- hospitals%>%filter(Facility.State == "VA")
WA<- hospitals%>%filter(Facility.State == "WA")
WV<- hospitals%>%filter(Facility.State == "WV")
WI<- hospitals%>%filter(Facility.State == "WI")
WY<- hospitals%>%filter(Facility.State == "WY")
```


```{r}
states <- c("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY")
```

```{r}
states_ratings <- c(mean(AL$Rating.Overall), mean(AK$Rating.Overall), mean(AZ$Rating.Overall), mean(AR$Rating.Overall), mean(CA$Rating.Overall), mean(CO$Rating.Overall), mean(CT$Rating.Overall), mean(DE$Rating.Overall), mean(DC$Rating.Overall), mean(FL$Rating.Overall), mean(GA$Rating.Overall), mean(HI$Rating.Overall), mean(ID$Rating.Overall), mean(IL$Rating.Overall), mean(IN$Rating.Overall), mean(IA$Rating.Overall), mean(KS$Rating.Overall), mean(KY$Rating.Overall), mean(LA$Rating.Overall), mean(ME$Rating.Overall), mean(MD$Rating.Overall), mean(MA$Rating.Overall), mean(MI$Rating.Overall), mean(MS$Rating.Overall), mean(MO$Rating.Overall), mean(MT$Rating.Overall), mean(NE$Rating.Overall), mean(NV$Rating.Overall), mean(NH$Rating.Overall), mean(NJ$Rating.Overall), mean(NM$Rating.Overall), mean(NY$Rating.Overall), mean(NC$Rating.Overall), mean(ND$Rating.Overall), mean(OH$Rating.Overall), mean(OK$Rating.Overall), mean(OR$Rating.Overall), mean(PA$Rating.Overall), mean(PR$Rating.Overall), mean(RI$Rating.Overall), mean(SC$Rating.Overall), mean(SD$Rating.Overall), mean(TN$Rating.Overall), mean(TX$Rating.Overall), mean(UT$Rating.Overall), mean(VT$Rating.Overall), mean(VI$Rating.Overall), mean(VA$Rating.Overall), mean(WA$Rating.Overall), mean(WV$Rating.Overall), mean(WI$Rating.Overall), mean(WY$Rating.Overall))
```

```{r}
states_and_ratings <- data.frame(states, states_ratings)
ggplot(states_and_ratings)+geom_col(mapping=aes(x=states, fill=states, y=states_ratings))+
  scale_x_discrete(guide = guide_axis(angle = 90))+
  ggtitle("Mean Overall Rating for Hospitals By State")+
  xlab("State")+
  ylab("Mean Overall Ratings for All Hospitals in the State")
```

```{r}
states_hip_knee <- c(mean(AL$`Procedure.Hip Knee.Cost`), mean(AK$`Procedure.Hip Knee.Cost`), mean(AZ$`Procedure.Hip Knee.Cost`), mean(AR$`Procedure.Hip Knee.Cost`), mean(CA$`Procedure.Hip Knee.Cost`), mean(CO$`Procedure.Hip Knee.Cost`), mean(CT$`Procedure.Hip Knee.Cost`), mean(DE$`Procedure.Hip Knee.Cost`), mean(DC$`Procedure.Hip Knee.Cost`), mean(FL$`Procedure.Hip Knee.Cost`), mean(GA$`Procedure.Hip Knee.Cost`), mean(HI$`Procedure.Hip Knee.Cost`), mean(ID$`Procedure.Hip Knee.Cost`), mean(IL$`Procedure.Hip Knee.Cost`), mean(IN$`Procedure.Hip Knee.Cost`), mean(IA$`Procedure.Hip Knee.Cost`), mean(KS$`Procedure.Hip Knee.Cost`), mean(KY$`Procedure.Hip Knee.Cost`), mean(LA$`Procedure.Hip Knee.Cost`), mean(ME$`Procedure.Hip Knee.Cost`), mean(MD$`Procedure.Hip Knee.Cost`), mean(MA$`Procedure.Hip Knee.Cost`), mean(MI$`Procedure.Hip Knee.Cost`), mean(MS$`Procedure.Hip Knee.Cost`), mean(MO$`Procedure.Hip Knee.Cost`), mean(MT$`Procedure.Hip Knee.Cost`), mean(NE$`Procedure.Hip Knee.Cost`), mean(NV$`Procedure.Hip Knee.Cost`), mean(NH$`Procedure.Hip Knee.Cost`), mean(NJ$`Procedure.Hip Knee.Cost`), mean(NM$`Procedure.Hip Knee.Cost`), mean(NY$`Procedure.Hip Knee.Cost`), mean(NC$`Procedure.Hip Knee.Cost`), mean(ND$`Procedure.Hip Knee.Cost`), mean(OH$`Procedure.Hip Knee.Cost`), mean(OK$`Procedure.Hip Knee.Cost`), mean(OR$`Procedure.Hip Knee.Cost`), mean(PA$`Procedure.Hip Knee.Cost`), mean(PR$`Procedure.Hip Knee.Cost`), mean(RI$`Procedure.Hip Knee.Cost`), mean(SC$`Procedure.Hip Knee.Cost`), mean(SD$`Procedure.Hip Knee.Cost`), mean(TN$`Procedure.Hip Knee.Cost`), mean(TX$`Procedure.Hip Knee.Cost`), mean(UT$`Procedure.Hip Knee.Cost`), mean(VT$`Procedure.Hip Knee.Cost`), mean(VI$`Procedure.Hip Knee.Cost`), mean(VA$`Procedure.Hip Knee.Cost`), mean(WA$`Procedure.Hip Knee.Cost`), mean(WV$`Procedure.Hip Knee.Cost`), mean(WI$`Procedure.Hip Knee.Cost`), mean(WY$`Procedure.Hip Knee.Cost`))
```

```{r}
states_and_hip_knee <- data.frame(states, states_hip_knee)
ggplot(states_and_hip_knee)+geom_col(mapping=aes(x=states, fill=states, y=states_hip_knee))+
  scale_x_discrete(guide = guide_axis(angle = 90))+
  ggtitle("Mean Cost for A Hip-Knee Procedure by State")+
  xlab("State")+
  ylab("Mean Cost for Hip-Knee Procedures in the State")
```

```{r}
states_ha <- c(mean(AL$`Procedure.Heart Attack.Cost`), mean(AK$`Procedure.Heart Attack.Cost`), mean(AZ$`Procedure.Heart Attack.Cost`), mean(AR$`Procedure.Heart Attack.Cost`), mean(CA$`Procedure.Heart Attack.Cost`), mean(CO$`Procedure.Heart Attack.Cost`), mean(CT$`Procedure.Heart Attack.Cost`), mean(DE$`Procedure.Heart Attack.Cost`), mean(DC$`Procedure.Heart Attack.Cost`), mean(FL$`Procedure.Heart Attack.Cost`), mean(GA$`Procedure.Heart Attack.Cost`), mean(HI$`Procedure.Heart Attack.Cost`), mean(ID$`Procedure.Heart Attack.Cost`), mean(IL$`Procedure.Heart Attack.Cost`), mean(IN$`Procedure.Heart Attack.Cost`), mean(IA$`Procedure.Heart Attack.Cost`), mean(KS$`Procedure.Heart Attack.Cost`), mean(KY$`Procedure.Heart Attack.Cost`), mean(LA$`Procedure.Heart Attack.Cost`), mean(ME$`Procedure.Heart Attack.Cost`), mean(MD$`Procedure.Heart Attack.Cost`), mean(MA$`Procedure.Heart Attack.Cost`), mean(MI$`Procedure.Heart Attack.Cost`), mean(MS$`Procedure.Heart Attack.Cost`), mean(MO$`Procedure.Heart Attack.Cost`), mean(MT$`Procedure.Heart Attack.Cost`), mean(NE$`Procedure.Heart Attack.Cost`), mean(NV$`Procedure.Heart Attack.Cost`), mean(NH$`Procedure.Heart Attack.Cost`), mean(NJ$`Procedure.Heart Attack.Cost`), mean(NM$`Procedure.Heart Attack.Cost`), mean(NY$`Procedure.Heart Attack.Cost`), mean(NC$`Procedure.Heart Attack.Cost`), mean(ND$`Procedure.Heart Attack.Cost`), mean(OH$`Procedure.Heart Attack.Cost`), mean(OK$`Procedure.Heart Attack.Cost`), mean(OR$`Procedure.Heart Attack.Cost`), mean(PA$`Procedure.Heart Attack.Cost`), mean(PR$`Procedure.Heart Attack.Cost`), mean(RI$`Procedure.Heart Attack.Cost`), mean(SC$`Procedure.Heart Attack.Cost`), mean(SD$`Procedure.Heart Attack.Cost`), mean(TN$`Procedure.Heart Attack.Cost`), mean(TX$`Procedure.Heart Attack.Cost`), mean(UT$`Procedure.Heart Attack.Cost`), mean(VT$`Procedure.Heart Attack.Cost`), mean(VI$`Procedure.Heart Attack.Cost`), mean(VA$`Procedure.Heart Attack.Cost`), mean(WA$`Procedure.Heart Attack.Cost`), mean(WV$`Procedure.Heart Attack.Cost`), mean(WI$`Procedure.Heart Attack.Cost`), mean(WY$`Procedure.Heart Attack.Cost`))
```

```{r}
states_and_ha <- data.frame(states, states_ha)
ggplot(states_and_ha)+geom_col(mapping=aes(x=states, fill=states, y=states_ha))+
  scale_x_discrete(guide = guide_axis(angle = 90))+
  ggtitle("Mean Cost for a Heart Attack Procedure for Hospitals By State")+
  xlab("State")+
  ylab("Mean Cost for Heart Attack Procedure in the State")
```

```{r}
myPalette2 <- brewer.pal(5, "Set2") 

ggplot(states_and_ratings, aes(x=states_ratings)) + 
  geom_histogram(binwidth=1, fill=myPalette2, color="#FFFFFF")+
  ggtitle("Histogram of States and Ratings")+
  xlab("Overall Rating")+
  ylab("Count (How Many States Have the Rating")
```


